apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: discovery-operator-mce-25
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: discovery-operator-mce-25
    app.kubernetes.io/part-of: release-mce-25
  name: discovery-operator-mce-25
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: discovery-operator-mce-25
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: discovery-operator-mce-25
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-25/discovery-operator-mce-25@sha256:988ceeb006455f7948bc4dc028547ea38a898290ac1e8b72f4303a49c53e6967
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources: {}
status: {}
