apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: managed-serviceaccount-mce-25
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-25/managed-serviceaccount-mce-25@sha256:b39df88c347f92e786a4ab164e5c3d6306c4c206d6d4d1aa17bbc42720cfafc3
        name: container-image
        resources: {}
status: {}
