apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: discovery-operator-tests-mce-25
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-25/discovery-operator-tests-mce-25@sha256:525fa8c69895b5c20917891a48c51580dd7af029b9a643293167dab44ac8952a
        name: container-image
        resources: {}
status: {}
