apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: discovery-operator-tests-mce-25
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: discovery-operator-tests-mce-25
    app.kubernetes.io/part-of: release-mce-25
  name: discovery-operator-tests-1mol
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: discovery-operator-tests-mce-25
    weight: 100
status: {}
