apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: work-mce-25
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: work-mce-25
    app.kubernetes.io/part-of: release-mce-25
  name: work-mce-25
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: work-mce-25
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: work-mce-25
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-25/work-mce-25@sha256:9ebb2d13338a7459e2006ca85d3fef8a1f25649836d72fabf64171d5523403ed
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources: {}
status: {}
