apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: addon-manager-mce-25
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: addon-manager-mce-25
    app.kubernetes.io/part-of: release-mce-25
  name: addon-manager-mce-25
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: addon-manager-mce-25
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: addon-manager-mce-25
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-25/addon-manager-mce-25@sha256:6dc60332064fc3ebe3c31867b45b6fec51966709508baacc6be25ff6c848019e
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources: {}
status: {}
