apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: backplane-operator-mce-25
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backplane-operator-mce-25
    app.kubernetes.io/part-of: release-mce-25
  name: backplane-operator-mce-25
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: backplane-operator-mce-25
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: backplane-operator-mce-25
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-25/backplane-operator-mce-25@sha256:88040cfd6da9b9b441bff14d4e68d6d7570180895a22fa0736dc48de15cc8dee
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources: {}
status: {}
