apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hypershift-addon-operator-mce-25
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hypershift-addon-operator
    app.kubernetes.io/part-of: release-mce-25
  name: hypershift-addon-operator-mce-25
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: hypershift-addon-operator-mce-25
status:
  loadBalancer: {}
