apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: console-mce-mce-25
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: console-mce-mce-25
    app.kubernetes.io/part-of: release-mce-25
  name: console-mce-mce-25
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: console-mce-mce-25
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: console-mce-mce-25
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-25/console-mce-mce-25@sha256:9e930d18782c2e130cb10aa61aa632d0fcdfed2a48662c6c6b03cc14bbc80c75
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources: {}
status: {}
