apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: console-mce-mce-25
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-25/console-mce-mce-25@sha256:c4a7838dc87c9381b871c8aeca87867a04f7cb507e40ccbfa79bb481cc58a99f
        name: container-image
        resources: {}
status: {}
