apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: managedcluster-import-controller-addon-mce-25
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: managedcluster-import-controller-addon-mce-25
    app.kubernetes.io/part-of: release-mce-25
  name: managedcluster-import-controller-addon-mce-25
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: managedcluster-import-controller-addon-mce-25
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: managedcluster-import-controller-addon-mce-25
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-25/managedcluster-import-controller-addon-mce-25@sha256:e338d55c79f9a1205b28d62e6161fd4807d9bfbb8e0b186862836c37ff1bd136
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources: {}
status: {}
