apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: managed-serviceaccount-mce-25
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: managed-serviceaccount-mce-25
    app.kubernetes.io/part-of: release-mce-25
  name: managed-serviceaccount-mce-25
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: managed-serviceaccount-mce-25
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: managed-serviceaccount-mce-25
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-25/managed-serviceaccount-mce-25@sha256:44f2ba809f973faa77f41218152166f53af433ec3d7693f152caa7fd0f91612c
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources: {}
status: {}
