apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hypershift-release-mce-25
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hypershift-release-mce-25
    app.kubernetes.io/part-of: release-mce-25
  name: hypershift-release-mce-25
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: hypershift-release-mce-25
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: hypershift-release-mce-25
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-25/hypershift-release-mce-25@sha256:25cf9835ed3bb5e8133463a39d3ac10056ecc1c7986bfc1c0e28424e22b7e509
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 9090
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
